config/routes.rb
Futamericano::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config


  localized([:es, :en]) do
    resource :channels, only: :show
    resource :soon, only: :show, controller: :soon
    #resources :teams
    #resource :home, :only => :show, :controller => :home
    #resource :scores, :only => :show
    #resource :standings, :only => :show
    #resource :contacts, :only => [:show, :create]
  end


  #namespace :live do
  #  resource :scores, :only => :show
  #end


  #namespace :api do
  #  resource :live_scores, :only => :show, :path => 'live'
  #  resource :game_channels, :only => :show
  #end


  root to: 'soon#show'

end



#== Route Map
# Generated on 12 Jul 2012 01:17
#
#                       soon POST       /soon(.:format)                     soons#create
#                   new_soon GET        /soon/new(.:format)                 soons#new
#                  edit_soon GET        /soon/edit(.:format)                soons#edit
#                            GET        /soon(.:format)                     soons#show
#                            PUT        /soon(.:format)                     soons#update
#                            DELETE     /soon(.:format)                     soons#destroy
#                       root            /                                   soon#show

app/views/shared/_like_button.html.haml
.fb_placeholder
  #fb-root

  :javascript
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

  .fb-like{'data-layout' => 'button_count', 'data-href' => 'http://facebook.com/FutAmericano',
           'data-send' => 'false', 'data-width' => 90, 'data-show-faces' => 'false'}

app/views/shared/_menu.html.haml
%span
  = link_to t('Scoreboard'), '#scores' #scores_path #TODO: add proper links after implementing functionality

%span
  = link_to t('Standings'), '#standings' #standings_path

%span
  = link_to t('TV Guide'), channels_path